spring:
  config:
    activate:
      on-profile: "oauth"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 392161708367-u1m20knrmlqvk9eb30gln46b5stssqkj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: rROnJ9aRm0i6kpRVs4Us
            client-secret: NmkWZBtRCf
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
