spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2_db/1.4.200/webservice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  profiles:
    include: oauth

# mustache 한글 깨짐 문제 해결
server:
  servlet:
    encoding:
      force-response: true
